name: nomixe
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  state_notifier: ^0.7.2+1
  riverpod: ^2.4.9
  connectivity_plus: ^5.0.2
  loading_animations: ^2.2.0
  dio: ^5.4.0
  dartz: ^0.10.1
  auto_route: ^7.8.0
  equatable: ^2.0.5
  flutter_riverpod: ^2.4.9
  flutter_svg: ^2.0.7

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  mocktail: ^0.3.0
  state_notifier_test: ^0.0.9
  test_coverage_badge: ^0.2.0
  http_mock_adapter: ^0.4.4
  json_serializable: ^6.5.3

flutter:
  uses-material-design: true

  assets:
    - assets/
